title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://rainchat.github.io/test

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
